variables:
  # When using dind service, you must instruct docker to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # If you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2375 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2375
  #
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE: "registry.hzdr.de/marie.houillon/cardiomechanics/cardiomechanics"
  DOCKER_THIRDPARTY_VTK: "registry.hzdr.de/marie.houillon/cardiomechanics/thirdparty-vtk"
  DOCKER_THIRDPARTY_OPENMPI_PETSC: "registry.hzdr.de/marie.houillon/cardiomechanics/thirdparty-openmpi-petsc"

stages:
  - build
  - test
  - deploy

build-docker-thirdparty-vtk:
  stage: build
  image: docker:20.10.17-dind
  rules:
  - if: $CI_COMMIT_BRANCH == 'main'
    changes:
      - docker/Dockerfile-thirdparty-vtk
  services:
  - docker:dind
  before_script:
  - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.hzdr.de
  script:
  - docker pull $DOCKER_THIRDPARTY_VTK || true
  - docker build --pull --no-cache -t $DOCKER_THIRDPARTY_VTK -f docker/Dockerfile-thirdparty-vtk .
  - docker push $DOCKER_THIRDPARTY_VTK
  after_script:
  - docker logout registry.hzdr.de
  tags:
  - docker,dind

build-docker-thirdparty-openmpi-petsc:
  stage: build
  image: docker:20.10.17-dind
  rules:
  - if: $CI_COMMIT_BRANCH == 'main'
    changes:
      - docker/Dockerfile-thirdparty-openmpi-petsc
  services:
  - docker:dind
  before_script:
  - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.hzdr.de
  script:
  - docker pull $DOCKER_THIRDPARTY_OPENMPI_PETSC || true
  - docker build --pull --no-cache -t $DOCKER_THIRDPARTY_OPENMPI_PETSC -f docker/Dockerfile-thirdparty-openmpi-petsc .
  - docker push $DOCKER_THIRDPARTY_OPENMPI_PETSC
  after_script:
  - docker logout registry.hzdr.de
  tags:
  - docker,dind

build-docker-image:
  stage: build
  image: docker:20.10.17-dind
  only:
  - main
  services:
  - docker:dind
  before_script:
  - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.hzdr.de
  script:
  - docker pull $DOCKER_IMAGE || true
  - |
    docker build --pull --no-cache -t $DOCKER_IMAGE -f docker/Dockerfile \
      --build-arg VTK_IMAGE=$DOCKER_THIRDPARTY_VTK \
      --build-arg OPENMPI_PETSC_IMAGE=$DOCKER_THIRDPARTY_OPENMPI_PETSC .
  - docker push $DOCKER_IMAGE
  after_script:
  - docker logout registry.hzdr.de
  tags:
  - docker,dind
