FROM ubuntu:22.04

WORKDIR /CardioMechanics

RUN apt update && apt install -y build-essential gfortran python3 git cmake autoconf libtool
ENV VTK_VERSION=v9.2.6

# env variables for CardioMechanics
ENV kaRootDir=/CardioMechanics
ENV THIRDPARTY_HOME=$kaRootDir/thirdparty
RUN mkdir -p ${THIRDPARTY_HOME}/src
ENV prefixPath=${THIRDPARTY_HOME}/install

# compile vtk
WORKDIR $THIRDPARTY_HOME/src
RUN apt install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev
RUN git clone --depth 1 --branch ${VTK_VERSION} https://gitlab.kitware.com/vtk/vtk.git vtk-${VTK_VERSION}
WORKDIR $THIRDPARTY_HOME/src/vtk-${VTK_VERSION}
# we have to rename a variable to avoid a redeclaration under Linux
RUN echo "Replacing HZ with H_Z in VTK..."
RUN grep -rl HZ . | xargs sed -i 's/HZ/H_Z/g'
RUN mkdir build && cd build && cmake .. -D CMAKE_INSTALL_PREFIX=${prefixPath}/vtk-${VTK_VERSION} && make && make install

