FROM ubuntu:22.04

WORKDIR /CardioMechanics

RUN apt update && apt install -y build-essential gfortran python3 git cmake autoconf libtool
ENV MPI_VERSION=v4.1.5
ENV PETSC_VERSION=v3.19.1

# env variables for CardioMechanics
ENV kaRootDir=/CardioMechanics
ENV THIRDPARTY_HOME=$kaRootDir/thirdparty
RUN mkdir -p ${THIRDPARTY_HOME}/src
ENV prefixPath=${THIRDPARTY_HOME}/install

# Compile OpenMPI
ENV AUTOMAKE_JOBS=1
WORKDIR ${THIRDPARTY_HOME}/src
RUN apt install -y flex
RUN git clone --depth 1 --branch ${MPI_VERSION} https://github.com/open-mpi/ompi.git openmpi-${MPI_VERSION}

WORKDIR ${THIRDPARTY_HOME}/src/openmpi-${MPI_VERSION}
RUN ./autogen.pl && ./configure --prefix=${prefixPath}/openMPI-64bit
RUN make -j && make install

# compile PETSc
WORKDIR $THIRDPARTY_HOME/src
RUN apt install -y libopenblas-dev
RUN git clone --depth 1 --branch ${PETSC_VERSION} https://gitlab.com/petsc/petsc.git petsc-${PETSC_VERSION}
WORKDIR $THIRDPARTY_HOME/src/petsc-${PETSC_VERSION}
RUN ./configure --prefix=${prefixPath}/petsc-${PETSC_VERSION} --with-cmake=1 --with-mpi-dir=${prefixPath}/openMPI-64bit --download-superlu --download-superlu_dist --download-mumps --download-dmumps  --download-metis --download-parmetis --download-bison --download-ptscotch --download-scalapack --download-blacs --download-hypre --with-shared-libraries=0 --with-x=0 COPTFLAGS=-O3 CXXOPTFLAGS=-O3 FOPTFLAGS=-O3 --with-debugging=no
RUN make all
RUN make install
RUN make PETSC_DIR=${prefixPath}/petsc-${PETSC_VERSION} PETSC_ARCH="" check

